apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
  name: sri-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2-retain
  volumeMode: Filesystem
  volumeName: sri-pv